CREATE DATABASE company;
USE company;

CREATE TABLE payment (
customer_id INT PRIMARY KEY,
customer VARCHAR(100),
mode VARCHAR(20) NOT NULL,
city VARCHAR(20)
);

INSERT INTO payment
(customer_id,customer,mode,city)
VALUES 
(101,"OLIVIA BARRETT","NETBANKING","PORTLAND"),
(102,"ETHAN SINCLAIR","CREDIT CARD","MIAMI"),
(103,"MAYA HEMANDEZ","CREDIT CARD","SEATTLE"),
(104,"LIAM DONOVAN","NETBANKING","DENVER"),
(105,"SOPHIA NGUYEN","CREDIT CARD","NEW ORLEANS"),
(106,"CALEB FOSTER","DEBIT CARD","MINNEAPOLIS"),
(107,"AVA PATEL","DEBIT CARD","PHOENIX"),
(108,"LUCAS CARTER","NETBANKING","BOSTON"),
(109,"ISABELLA MARTINEZ","NETBANKING","NASHVILLE"),
(110,"JACKSON BROOKS","CREDIT CARD","BOSTON");

# Find the total payment according to each payment method.
SELECT mode,COUNT(customer_id)
FROM payment
GROUP BY mode;